export const types = {

    FETCH_DATA: "FETCH_DATA",

    UPDATE_STATE: "UPDATE_STATE",
    REMOVE_DATA: "REMOVE_DATA",

    SET_STATE: "SET_STATE",
    UNSET_STATE: "UNSET_STATE",

    FILL_STATE: "FILL_STATE",
    DROP_STATE: 'DROP_STATE',

}